### ISSUE TITLE
Hide UI elements from printed hyper-readings

### ISSUE THREAD

**Issue by e-e-e** [e-e-e/hyper-reader#31]
This should be as simple as adding this css to elements that we do not want displayed.

```css
@media print
{    
    .no-print, .no-print *
    {
        display: none !important;
    }
}
```
